import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from "./components/Navbar"
import { Suspense } from 'react'
import Loading from './loading'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Utsav\'s Personal Website',
  description: 'Generated by create next app',
}


export default function RootLayout({children}) {

  return (
    <html lang="en" className="scroll-smooth bg-main">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet"/>
      </head>
      <body>
        <main className="app bg-gradient-to-r from-blue-1 to-blue-2 text-white">
          <Navbar/>
            <Suspense fallback={<Loading />}>{children}</Suspense>
        </main>
      </body>
    </html>
  )
}
